name: Update Major Tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update major tag
        uses: artryazanov/update-major-tag-action@v1
